### ISSUE TITLE
Partition Morton Code Range Swapped In Dimensions

### ISSUE THREAD

**Issue by weshoke** [Forceflow/ooc_svo_builder#48]
Going off of the name of the arguments for `morton3D_64_Decode_LUT_shifted`
```
inline void morton3D_64_Decode_LUT_shifted(const uint_fast64_t morton, uint_fast32_t& x, uint_fast32_t& y, uint_fast32_t& z){
```

Seems that the wrong parts of the AABB limit vectors are being passed in:
```
morton3D_64_Decode_LUT_shifted(morton_start, p_bbox_grid.min[2], p_bbox_grid.min[1], p_bbox_grid.min[0]);
```

Shouldn't this be
```
morton3D_64_Decode_LUT_shifted(morton_start, p_bbox_grid.min[0], p_bbox_grid.min[1], p_bbox_grid.min[2]);
```

https://github.com/Forceflow/ooc_svo_builder/blob/master/src/svo_builder/voxelizer.cpp#L146

**Comment by Forceflow** [comment]
Not sure - I think I do this because the model already got flipped somewhere in the conversion process, and this is a dirty hack to counter that. I'll change it to your suggestion, and see what the output is in model form.
