### ISSUE TITLE
findFirstSetBit functions in libmorton don't compile

### ISSUE THREAD

**Issue by weshoke** [Forceflow/ooc_svo_builder#49]
https://gcc.gnu.org/onlinedocs/gcc-4.5.0/gcc/Other-Builtins.html
```
— Built-in Function: int __builtin_ffs (unsigned int x)
Returns one plus the index of the least significant 1-bit of x, or if x is zero, returns zero.
```

The signature returns an int, but the assignment is to an `unsigned long *`.

https://github.com/Forceflow/ooc_svo_builder/blob/master/src/libs/libmorton/include/morton_common.h#L32

Also, the 64 variant has the identifier name misspelled `first_bit_location` v. `firstbit_location`.

**Comment by Forceflow** [comment]
Should be fixed in latest libmorton update?
