### ISSUE TITLE
OctreeBuilder::addVoxel(const uint64_t morton_number) fails

### ISSUE THREAD

**Issue by Degot** [Forceflow/ooc_svo_builder#51]
assert(d-1 >= 0) fails, when morton_number is less than b_current_morton.

`if (morton_number != b_current_morton){
		fastAddEmpty(morton_number - b_current_morton);
	}`

**Comment by Forceflow** [comment]
Because you're not supposed to feed the OctreeBuilder nodes that are not ordered - you can only feed it voxels of increasing morton order, otherwise the building algorithm doesn't work - the whole point is that you're working on a stream of morton-ordered voxels.

**Comment by galixiad** [comment]
got it
