### ISSUE TITLE
voxelize_schwarz_method fails for multi partition

### ISSUE THREAD

**Issue by Degot** [Forceflow/ooc_svo_builder#52]
`char* voxels = new char[(size_t)morton_part];`

`auto index = morton3D_64_encode(z, y, x);  <-- index is always less than morton_part;`
as result [index - morton_start] is less than 0 for 2nd partition, where morton_start is > 0
`if (voxels[index - morton_start] == FULL_VOXEL) { continue; }`

**Comment by Forceflow** [comment]
I think I fixed this by doing morton3D_64_encode(x,y,z) in latest commit - I can't remember why I ever switched that to (z,y,x)

**Comment by Forceflow** [comment]
Hey @Degot , I fixed this pesky bug in the latest release! Should be gone now, tested it on a lot of models with a lot of partitions. (HInt: set memory limit ridiculously low, like 128 Mb).
