### ISSUE TITLE
OctreeBuilder::finalizeTree() fails 

### ISSUE THREAD

**Issue by Degot** [Forceflow/ooc_svo_builder#53]
Exception in finalizeTree(), because b_buffers doesn't have [0][0].
`writeNode(node_out, b_buffers[0][0], b_node_pos);`

**Comment by Forceflow** [comment]
Hm, I'm having no problems building an SVO over a model (stanford bunny) in 64 partitions, see my output here: http://pastebin.com/giWrsxhF

What model are you trying this on, and with which parameters are you launching the tool?

**Comment by Degot** [comment]
I'm using powerplant.ply

**Comment by Forceflow** [comment]
Have you tried doing this using the new release? @Degot 

Fixed a nasty bug that had implications on several parts of the pipeline, might have magically fixed your problem as well :fingerscrossed:

**Comment by Degot** [comment]
Hi, now it's ok, 
FYI: with  -s 65536  it requires 2kk partitions for 1024 MB limit.  It fails , while "freezing" OS =)

**Comment by Forceflow** [comment]
Probably too many file allocations in that case :p Which OS?

**Comment by Degot** [comment]
win 2k12r2

**Comment by bitxue** [comment]
With '-s 65536', how much disk storage size will the generated SVO take up?

**Comment by Forceflow** [comment]
@bitxue : Really worst case scenario (non-sparse model, fat voxel tree with color and normals), about 8 petabyte :)

But probably a **lot** less (several orders of magnitude) if you're just using a simple voxel tree, and even less if you're compressing into a Directed Acyclic Graph (DAG).
