### ISSUE TITLE
Wrong constants in bitshift

### ISSUE THREAD

**Issue by weshoke** [Forceflow/ooc_svo_builder#57]
The 46 should be 45:
https://github.com/Forceflow/ooc_svo_builder/blob/master/src/libs/libmorton/include/morton3D_64.h#L232

**Comment by Forceflow** [comment]
Well spotted. I've got some health issues at the moment, but after that I'm working on a more thorough testing set.

**Comment by Forceflow** [comment]
(Fixed in latest Libmorton version, included)
