### ISSUE TITLE
cannot bind non-const lvalue reference of type ‘uint_fast32_t&...

### ISSUE THREAD

**Issue by Kinianox** [Forceflow/ooc_svo_builder#60]
I am trying to build svo via build_svo_builder.sh on Ubuntu 18.04, but an error occurs:

../src/svo_builder/svo_builder_util.h: In function ‘glm::vec3 mortonToRGB(uint64_t, size_t)’:
../src/svo_builder/svo_builder_util.h:15:40: error: cannot bind non-const lvalue reference of type ‘uint_fast32_t& {aka long unsigned int&}’ to an rvalue of type ‘uint_fast32_t {aka long unsigned int}’
  morton3D_64_decode(morton_number,z,y,x);

Could you check the issue and give me some advice, thank you.

**Comment by Forceflow** [comment]
Looking into it!

**Comment by Forceflow** [comment]
Should be fixed in commit 54e8edec04a78e5f84fdf5f15af3c2578a12772d

**Comment by Kinianox** [comment]
Thanks
