### ISSUE TITLE
Question - positions of intermediate voxels

### ISSUE THREAD

**Issue by Ervadar** [Forceflow/ooc_svo_builder#63]
Hi! Is there any way for this program to generate the positions of intermediate voxels or do I have to do it myself somehow?

Also, if not, then how should I approach this? Let's say the root node has position (0, 0, 0) and it has 8 children (intermediate nodes). Can I, just now, exactly deduce the positions of those 8 children?

**Comment by Forceflow** [comment]
The positions of the (centers of the) leaf voxels are determined by their position in the tree and the (cubical) size of the entire grid.

The root node in a Sparse Voxel Octree can be interpreted as a big fat voxel containing the entire grid space, with its center in the middle of the grid.

**Comment by Ervadar** [comment]
I was talking about INTERMEDIATE voxels, not LEAF voxels :)
But nevertheless, thank you for your answer!
